### ISSUE TITLE
Remove all unused/superseded/obsolet options and associated code

### ISSUE THREAD

**Issue by fradav** [diyabc/diyabc#14]
Removed : 
- ABC parameter estimation (superseded by RF)
- ABC computation of posterior probability of scenarios (superseded by RF)
- bias/precision computations (obsolet/unused)
- confidence in scenario choice computations (obsolet)
- ABC prior/scenario checking (unused)
- ABC model checking (obsolet)

**Comment by fradav** [comment]
Done in 86650522a90a41db4c10a3d0c74ebd479fb39154

**Comment by aestoup** [comment]
Hello Francois-david,
Peux tu STP réactiver l'option suivante = ABC prior/scenario checking.
Apres discussion avec pas mal d'utilisateurs, c'est une option de "pre-traitement" tres appreciée!
Elle marche sur un reftable donc en principe pas de pbl a entrevoir.
J'ai deja vu avec Ghislain ou l'appeler dans l'interface.
Par avance merci.
A.
