### ISSUE TITLE
DTA summary stats 

### ISSUE THREAD

**Issue by fradav** [diyabc/diyabc#16]
@elombaert : 

> Ci-joint un projet dans lequel j’ai eu ce souci. Si vous regardez le fichier "first_records_of_the_reference_table_0.txt", la colonne DTA_2_3 (D de Tajima de la pop 3), vous verrez que tout est à 0. Pourtant, il y a régulièrement du polymorphisme dans cette pop 3 (jusqu’à 3 haplotype puisqu’il n’y a que 3 individus avec séquence pour cette pop ; cf. colonne NHA_2_3 du même fichier). 

[Cydalima_perspectalis_Pop_Sha_War_Ke.txt](https://github.com/diyabc/diyabc/files/4388611/Cydalima_perspectalis_Pop_Sha_War_Ke.txt)
[first_records_of_the_reference_table_0.txt](https://github.com/diyabc/diyabc/files/4388612/first_records_of_the_reference_table_0.txt)
[header.txt](https://github.com/diyabc/diyabc/files/4388613/header.txt)

**Comment by fradav** [comment]
Refering to [Wikipedia's explanation](https://en.wikipedia.org/wiki/Tajima%27s_D)

**Comment by fradav** [comment]
And
[Choisy, M., Franck, P., & Cornuet, J. M. (2004). Estimating admixture proportions with microsatellites: comparison of methods based on simulated data. Molecular Ecology, 13(4), 955-968.](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1365-294X.2004.02107.x?casa_token=N30nROxjXQcAAAAA%3ARKebfQYvQS6ITo6Vo-_rDYPUPQYwWetto9_mrRyiL_EnL1zXjazy5k3cYwQ24tROIV3AeQQZ3xtGTdOr)

**Comment by aestoup** [comment]
On a fait des tests sur fichiers de data simulées et on a fait des calculs a la main avec Eric du D_tajima a partir des formules wikipedia.
On a une piste! En effet tout se passe comme si le programme DIYABC considére n-1 individus avec des sequences et donc quand on a 3 individus DIYABC pense qu'il y en a que 2 et du coup D_Tajima = 0.
Bref: voir dans le programme de JMC combien d'individus sont pris dans la boucle du calcul du D de Tajima. 
Note: POUR CONFIRMATION DE CETTE HYPOTHESE Eric va se fader qques calculs a la main supplementaires mimant la prise en compte de n-1 au lieu de n individus.

**Comment by elombaert** [comment]
Pour la stat DTA (Tajima’s D) sur séquence, j'ai fait des petits tests. J'ai utilisé 8 pops contenant 2 à 5 individus avec un seul marqueur mitochondrial (chaque individu au sein d'une pop ayant une séquence unique). J'ai calculé les DTA sous DIYABC avec les statobs, puis j'ai utilisé le logiciel Arlequin 3.5.2.2 pour calculer les D de Tajima sur le même dataset. Voici les résultats pour les 8 pops :

pop | n individus | DTA (diyabc) | DTA (Arlequin)
-- | -- | -- | --
1 | 2 | 0 | 0
2 | 3 | 0 | 0
3 | 4 | -0.78012299 | -0.78012
4 | 5 | -1.12397425 | -1.12397
5 | 2 | 0 | 0
6 | 3 | 0 | 0
7 | 4 | 0.26164772 | 0.26165
8 | 5 | 0.21000942 | 0.21001

Conclusion : excellente nouvelle, exactement la même chose !

Donc :
- il semble normal d'avoir 0 lorsqu'il n'y a que 3 individus (Arnaud et moi allons creuser pour bien comprendre).
- diyabc calcul correctement les DTA --> Ouf !

**Comment by elombaert** [comment]
Cette suspicion d’erreur dans le calcul du DTA était liée à l’impossibilité de faire des comparaisons de scénario en RF à l’aide d’abcrf lorsqu’une stat contenait toujours la même valeur dans le reftable (ici 0 pour les DTA avec seulement 3 individus). Le DTA est donc correctement calculé, mais le problème persiste : impossible de faire une comparaison de scénario sous abcrf dans ces situations. Le message d’erreur est le suivant :

> Error in lda.default(x, grouping, ...) : 
  variables 25 29 33 34 37 38 57 58 61 62 appear to be constant within groups

A noter que ça n’empêche pas de faire des estimations de paramètre. Logique si le problème est associé aux LDA.

Proposition :
Ces valeurs fixées (par exemple 0 pour le DTA) ne sont pas des erreurs. Ça peut d'ailleurs arriver pour d’autres stats. Par conséquent, l'idéal serait peut-être bien qu’AbcRanger scan le reftable, identifie les stats "constantes", les retire pour l’analyse, et envoie un petit message pour dire que des variables (et lesquelles) n’ont pas été utilisées car constante dans le reftable.

A discuter bien sûr : ça n’est qu’une proposition, et je ne sais même pas si c’est possible/faisable :)

**Comment by aestoup** [comment]
Excellent travail Eric: bravo! Comme quoi un bug peut amener des amelioration plus generales et tres interessantes!
Tu as raison, il y aura qques mini-ajustements a faire dans abcranger. Ca tombe bien FD est en maitrise totale de ce programme et donc il ca va etre plus simple pour lui que pour DIYABC.
Je vais discuter avec JM Marin pour bien cerner les tenants et aboutissants.

**Comment by fradav** [comment]
@elombaert j'entends ce que tu dis, mais en RF ça ne sert à pas à grand'chose, car par construction on zappe d'office toutes les covariables constantes qui n'apportent rien dans la discrimination des valeurs de sortie. À la limite ça pourrait économiser un peu de mémoire, et encore. 
Le problème de LDA est différent. En effet, trop de variables colinéaires risquent de faire planter la lda, celle d'abcrf est un peu tatillonne et refuse carrémment les variables constantes par classe. 
Avec abcranger, ce problème n'existe que si tu as plus de variables que d'observations, ce qui annule d'office l'intérêt de la LDA, il faut la désactiver.

**Comment by elombaert** [comment]
C'est génial si ça n'est pas un problème dans AbcRanger (que je n'ai en effet pas testé sur ce point). Je me demandais en revanche : pas de risque de problème du même genre lorsqu'on utilise les PLS pour les estimations de paramètre ?

**Comment by aestoup** [comment]
Hello a tous,
Jean-Michel Marin m'a envoyé un mail pour repondre a la question que je lui ai posé il y a qques jours:  "Quelles consequences quand on a une ou plusieurs stats du reftable (training set) avec des valeurs constantes pour toutes les particules du training set? Pbl pour random forest? Pbl pour LDA?
Voici sa réponse:
"Bonjour Arnaud et Eric,
Cela ne pose pas de difficulté aux forêts aléatoires, en fait la variable ne sera jamais sélectionnée.
Par contre, problème pour la construction des axes LDA.
En effet, pour LDA, il faut que la matrice de variance-covariance
du tableau de données soit inversible. Ce n'est pas le cas
si un variable est constante car sa variance est nulle.
Bref,, il faut supprimer les variables constantes.
Amitiés,
Jean-Michel"

FD et E: conclusion (proposition) = prevoir par "securité" de virer lors du passage dans abcranger les variables constantes du training set une fois ce dernier lu ? Dans ce cas indiquer un message dans le principal fichier d'output (et/ou dans la fenetre dos quand on run en ligne) du type "Warning: the summary statistics XXX , YYY et ZZZ show fixed values over the entire training set and have hence been removed from the latter before processing any analysis."

Ca vous va comme solution ?

**Comment by fradav** [comment]
ça ne pose pas de problème particulier, je ferai une issue à part.

**Comment by aestoup** [comment]
OK: je te fais confiance FD.

**Comment by fradav** [comment]
https://github.com/diyabc/abcranger/issues/51
