### ISSUE TITLE
MAF incorrectly computed for anything but autosomal

### ISSUE THREAD

**Issue by fradav** [diyabc/diyabc#17]
@elombaert :
J'ai fait des jeux de données simples avec les type A (autosomes diploïdes), H (quand espèce haploïde) ou M (pour ADN mitochondriale). Après vérification des vraies fréquences allélique, ça fait exactement ce à quoi on s'attendait (ici avec une MAF=0.05) :
> 
> - Sur A, la lecture du fichier dans DIYABC 2.1.0 me donne : 4 loci fitting the MAF (over 15) --> correct
> 
> - Sur H OU M : 5 loci fitting the MAF (over 15) --> la vraie valeur est 10 loci
> Dans ce cas-ci, la valeur "5" correspond effectivement à ce qu'on aurait en faisant le calcul de fréquences comme s'il s'agissait d'autosomes diploïdes.
> 

[TEST_MAF05_2pop_A.txt](https://github.com/diyabc/diyabc/files/4388629/TEST_MAF05_2pop_A.txt)
[TEST_MAF05_2pop_H.txt](https://github.com/diyabc/diyabc/files/4388630/TEST_MAF05_2pop_H.txt)
[TEST_MAF05_2pop_M.txt](https://github.com/diyabc/diyabc/files/4388631/TEST_MAF05_2pop_M.txt)

**Comment by fradav** [comment]
@aestoup : 

> SNP: 5 categories
> - autosomal = 2n
> - Adn_mt et haploide = n
> - Y = M (mâles)
> - X = 2F  (femelles) + M (mâles)
>  Attention aux données manquantes

**Comment by aestoup** [comment]
Pourrais tu STP m'envoyer par mail ou via/dans gitHub le code des deux procedures suivantes:

- celle qui calcule la MAF lors de la lecture du observed dataset file (= celle qui merde en dehors de autosomal et que on va adapter pour que ca fasse le job quand on a des locus NON autosomaux)

- celle qui calcule la MAF lors de la production de simulated data = il faut que je verifie que, comme cela semble etre le cas, cette procedure est clean.

Concretement, je vais tenter de proposer des modifications pour chaque type de marqueur (pas  codées clean = plutot  des grandes instructions selon le type de marqueur) de la procedure qui calcule la MAF lors de la lecture du observed dataset file.

Ca sera a toi de transcrire ca en code clean.

Ca te va comme ca?

Dis moi si tu veux proceder differemment.

**Comment by fradav** [comment]
Pour la simu:
```cpp
bool ParticleC::mafreached(int loc) {
	//cout<<"debut de mafreached(loc="<<loc<<")\n";
	int sa, indiv, n0, n1;
	double fam;
	n0 = 0;
	n1 = 0;
	//cat = (this->locuslist[loc].type % 5);
	for (sa = 0; sa < dataobs.nsample; sa++) {
		for (indiv = 0; indiv < this->locuslist[loc].samplesize[sa]; indiv++) {
			if (this->locuslist[loc].haplosnp[sa][indiv] == 0) n0++;
			else if (this->locuslist[loc].haplosnp[sa][indiv] == 1) n1++;
		}
	}
	if (n0 <= n1) fam = (double)n0 / (double)(n0 + n1);
	else fam = (double)n1 / (double)(n0 + n1);
	//cout<<"fin de mafreached\n";
	return (fam >= this->maf);
}
```

Pour l'observé : 
```cpp
			n0 = 0;
			n2 = 0;
			for (ech = 0; ech < this->nsample; ech++) {
				for (ind = 0; ind < this->nind[ech]; ind++) {
					//cout<<"sexe="<<this->indivsexe[ech][ind]<<"   genotype="<<genotype[ech][ind][loc]<<"\n";
					if ((this->locus[loc].type == 10)or ((this->locus[loc].type == 12)and (this->indivsexe[ech][ind] == 2))) {
						if (genotype[ech][ind][loc] == "0") n0 += 2;
						else if (genotype[ech][ind][loc] == "1") {
							n0++;
							n2++;
						}
						else if (genotype[ech][ind][loc] == "2") n2 += 2;
					}
					else {
						if (genotype[ech][ind][loc] == "0") n0++;
						else if (genotype[ech][ind][loc] == "1") n2++;
					}
				}
			}
			this->locus[loc].mono = (n0 + n2 < 1);
			if (not this->locus[loc].mono) {
				if (n0 <= n2) fam = (double)n0 / (double)(n0 + n2);
				else fam = (double)n2 / (double)(n0 + n2);
				this->locus[loc].mono = (fam < this->maf);
			}
			if (not this->locus[loc].mono) {
				nloc++;
			}
			else {
				cout << "le locus " << loc << " a une maf (" << fam << ") inférieure à la limite (" << this->maf << ")\n";
			}
```

**Comment by fradav** [comment]
Pour l'instant je ne comprends pas bien la différence entre les deux codes.

Par contre ce que je comprends c'est que pour l'observé, JMC utilise un raccourci en faisant le filtrage MAF **pendant** la purge des locus monomorphes et tous les locus de maf non atteinte sont comptés comme monomorphes (ce qui n'est pas tout à fait correct d'un point de vue biologique, je suppose).

**Comment by aestoup** [comment]
Je vais regarder ce code de plus pret ce jeudi apres midi ou demain. 
Ta proposition ci-dessous est peut etre ok mais pour le moment je n'ai pas eu le temps de voir ca pour te dire.
Ceci dit tu peux tenter ces petites modifs et faire un binaire que tu envoies a moi et surtout Eric pour voir ce que ca donne (avec tes cas tests Eric).
Si ca fait le job alors tant mieux.
Plus plus tard anyway
------------------------------------------

Si tu me dis que la fonction de la simu est correcte il suffit de remplacer les trois lignes dans le code:

				if (n0 <= n2) fam = (double)n0 / (double)(n0 + n2);

				else fam = (double)n2 / (double)(n0 + n2);

				this->locus[loc].mono = (fam < this->maf);

par :

this->locus[loc].mono = !mafreached(loc);

Explication: JMC utilise un raccourci en faisant le filtrage MAF pendant la purge des locus monomorphes et tous les locus de maf non atteinte sont comptés comme monomorphes (ce qui n'est pas tout à fait correct d'un point de vue biologique, je suppose).

Je fais ça et j'envoie un binaire.

**Comment by aestoup** [comment]
Piste a suivre:
Je pense avoir pigé ce qu'il faut changer dans la procedure "dataobs" ---> on pourra en discuter de vive voix par skype mais voila deja ci-dessous les explication et mes propositions:

Regarde la notice de DIYABC p 93:

"a second line starting with the three keywords IND SEX
POP, separated by at least one space, followed by as many letters as SNP loci, the letter giving the
location of the locus as above (< A > for autosomal diploid loci, < H > for autosomal haploid loci,
< X > for X-linked (or haplo-diploid) loci, < Y > for Y-linked loci and < M > for mitochondrial
loci). Letters are separated by a single space. as many lines as there are genotyped individuals,
with the code-name of the individual, a letter (M or F) indicating its sex, a code-name for its
population and the values (0, 1 or 2) of the number of the (arbitrarily chosen) reference allele at
each SNP locus. For instance in the case autosomal diploid SNP loci, we have 0 = homozygous
genotype for the non reference allele, 1 = heterozygous genotype for the reference allele, 2 =
homozygous genotype for the reference allele. It is worth noting that for autosomal haploid loci
(denoted H), as well as for mitochondrial loci (denoted M) and Y-linked loci (denoted Y), the
SNP genotypes will be 0 or 1."

et p 96 (exemple de fichier dataobs IndSeq)

Dans la procedure de JMC:

n0 est le compteur d'alleles de reference

n2 est le compteur de  l'allele alternatif

On pige bien que pour le cas qui marche bien avec le code actuel a savoir:

Locus autosomal diploide AVEC SEXE F, M ou 9 (note: on a des genotypes 0, 1 ou 2)

0 --> n0=+2

2 --> n2=+2

1 --> n0=+1 et n2=+1


Du coup pour les autres types de locus;

Haploid autosomal AVEC SEXE F, M ou 9 (note: on a des genotypes 0 ou 1)

0 --> n0=+1

1 --> n2=+1

ADNmt AVEC SEXE F, M ou 9 (note: on a des genotypes 0 ou 1)

0 --> n0=+1

1 --> n2=+1

Y-linked ssi AVEC SEX M (note: on a des genotypes 0 ou 1)

0 --> n0=+1

1 --> n2=+1

X-linked  (note: on a des genotypes 0, 1 ou 2 pour F et 0 ou 1 pour M)

AVEC SEX M

0 --> n0=+1

1 --> n2=+1

AVEC SEX F

0 --> n0=+2

2 --> n2=+2

1 --> n0=+1 et n2=+1

**Comment by fradav** [comment]
Alors on a fait tourner le general (le mien et celui de JMC) et le résultat des courses c'est que dans la sortie texte, il y a le bon nombre locus:
le locus 2 a une maf (0.030303) inférieure à la limite (0.05)
le locus 3 a une maf (0) inférieure à la limite (0.05)
le locus 5 a une maf (0) inférieure à la limite (0.05)
le locus 9 a une maf (0) inférieure à la limite (0.05)
le locus 12 a une maf (0) inférieure à la limite (0.05)
purge de 5 locus monomorphes

La seule réserve c'est que c'est incorrect : c'est 4 locus monomorphes et 1 locus filtrant la maf.
Le problème semble venir de l'interface qui n'interprète pas correctement le bon nombre de locus filtrés.
