### ISSUE TITLE
Incorrect handling of fixed locii for computing Admixture stat for sequences

### ISSUE THREAD

**Issue by fradav** [diyabc/diyabc#18]
While we have "correct" policies for this in microsat and snp, we overlooked it for sequences.

**Comment by fradav** [comment]
[Choisy, M., Franck, P., & Cornuet, J. M. (2004). Estimating admixture proportions with microsatellites: comparison of methods based on simulated data. Molecular Ecology, 13(4), 955-968.](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1365-294X.2004.02107.x?casa_token=N30nROxjXQcAAAAA%3ARKebfQYvQS6ITo6Vo-_rDYPUPQYwWetto9_mrRyiL_EnL1zXjazy5k3cYwQ24tROIV3AeQQZ3xtGTdOr)

**Comment by aestoup** [comment]
For sequence data = try first to simply transpose the code patch used for this stat computed for microsatellites...It might be enough to solve the pbl.
Then ask =Eric for a test

**Comment by fradav** [comment]
@elombaert tu écrivais :

> 3. La stat d’admixture des séquences ne fonctionne toujours pas. Souvent la valeur -999 est obtenue, et ça fait planter les analyses suivantes (reftable inutilisable). Je l’avais déjà signalé il y a longtemps car c’était déjà le cas sur DIYABC 2.1.0.


Est-ce que tu es sûr que c'est la stats d'admixture pour les séquences qui est concernée et pas celle des microsats ? Parce que le -999 est dans celle des microsats (AML) et pas dans celle des séquences (SML)...

**Comment by elombaert** [comment]
Je n'arrive pas à remettre la main sur un exemple qui m'avait produit des -999. Mais a priori, il s'agit bien des séquences (je pense n'avoir jamais vu ça sur les microsat).
En essayant de générer un reftable pour reproduire le problème avec diyabc 2.1.0, ça n'a pas fonctionné (erreur de segmentation...). Si on enlève les stats d'admixture séquences, ça fonctionne bien. Je te joins le projet en question.
[TEST_PB_STAT_ADMIX_SEQ_2020_4_2-1.zip](https://github.com/diyabc/diyabc/files/4421960/TEST_PB_STAT_ADMIX_SEQ_2020_4_2-1.zip)
Je vais quand même essayer de retrouver cette histoire de -999... ça me chiffonne...

**Comment by elombaert** [comment]
Ma stagiaire vient de m'envoyer ça :
[first_records_of_the_reference_table_1.txt](https://github.com/diyabc/diyabc/files/4421965/first_records_of_the_reference_table_1.txt)
Avec donc des -9999 à la fin sur les SML

**Comment by fradav** [comment]
J'arrive à reproduire ton segfault avec ton dossier de test (pas les -9999) mais je pense que je suis sur la bonne voie, étant donné que le crash se produit exactement dans la fonction d'admixture (en calcul sur les statobs), peut-être qu'il passe dans l'exemple de ta stagiaire mais qu'il délire quand même sur les simus... À suivre

**Comment by aestoup** [comment]
Exemple interessant: Il y a effectivement des valeurs -99999 a la fin a 
priori pour les SML...mais attention cf il y a un decalage des colonnes 
du au fait que les taux de mutations microsat et sequences n'apparaient 
pas dans le fichier...et en plus on voit des PID (microsat).

Bref, il faut s'assurer que les taux de mutations soient bien ecrit dans 
ce txt (et dans reftable.bin), virer les PID (en principe ca c'est 
fait), et voir si ce probleme de -99999 n'est pas lié a un pbl sur les 
taux de mutation ou un pbl sur la foction SML meme (dans ce cas patcher 
facon microsat).

In fine (apres corrections addocs dans le code)  il faudra refaire le 
meme run test que celui de la stagiaire Eric et voir si tout est resolu.


Le 02/04/2020 à 17:27, elombaert a écrit :

**Comment by aestoup** [comment]
Note: Pour voir ces pbl de decalage = ouvrir le fichier sous excel


Le 03/04/2020 à 12:03, Arnaud Estoup a écrit :

**Comment by fradav** [comment]
Ok j'ai trouvé le bug, la fonction d'admixture sequences a sa propre fonction dédiée de calculs des fréquences et celle-ci suppose systématiquement qu'il n'y a que 3 pops en tout et pour tout. ça plantait et/ou donnait des valeurs aberrantes dès qu'on passait à 4 pops. C'est corrigé, le binaire suivra.

**Comment by fradav** [comment]
Note si vous me donnez la méthode pour ouvrir le fichier.txt sous excel 2019 je suis preneur, ça marche pas pour aligner les colonnes.

**Comment by elombaert** [comment]
Voici le projet de ma stagiaire :
[TEST_PB_SEQ_ADMIXTURE.zip](https://github.com/diyabc/diyabc/files/4426675/TEST_PB_SEQ_ADMIXTURE.zip)
Il avait été simulé avec le dernier diyabc (donc avec les autres problèmes de stats), mais peu importe. Avec ça, tu devrais réussir à obtenir les -9999. A noter que j'ai lu le reftable.bin avec abcrf sous R : il semble que les -9999 correspondent bien aux SML.

**Comment by elombaert** [comment]
> Ok j'ai trouvé le bug, la fonction d'admixture sequences a sa propre fonction dédiée de calculs des fréquences et celle-ci suppose systématiquement qu'il n'y a que 3 pops en tout et pour tout. ça plantait et/ou donnait des valeurs aberrantes dès qu'on passait à 4 pops. C'est corrigé, le binaire suivra.

Génial ! (désolé pour le message d'avant, ton message m'était passé sous le nez)

**Comment by fradav** [comment]
@aestoup d'ailleurs c'est étrange cette présupposition du nombre de pops pour les séquences, t'as un avis dessus ?

**Comment by aestoup** [comment]
Oui c'est bizarre. Il faut calculer cette stats sur des triplets de pop 
ca c'est sur...

mais de la a dire si plus de trois pops dans le datafile on oublie la 
stat c'est pas normal.

Verifie que il n'y a pas une instruction de ce type pour les AML sur les 
microsats et les SNP. Cf. ca marche bien avec ces marqueurs donc si il y 
a ca aussi ca veut dire que la fonction incriminée ne fait pas ce que tu 
crois.

Apres c'est peut etre un oublie a la con...ca peut arriver. Si in fine 
ca marche correctement avec ton patch c'est l'essentiel. Eric confirmera.


Le 03/04/2020 à 13:16, fradav a écrit :

**Comment by fradav** [comment]
Ok j'ai compris ce qui s'est passé, c'est lors de la transition de l'ancien système de stats de Jean-Marie qui calculait toutes les stats par locus au nouveau système qui "accumule" les stats par locus. Le "3" pops était correct dans son code, pas dans le mien, ça m'avait échappé.

**Comment by aestoup** [comment]
Cool que tu es pigé ce truc: bravo


Le 03/04/2020 à 14:32, fradav a écrit :

**Comment by fradav** [comment]
Fixed in 11340a4319a23c3c4d8c7a0daa4c54d42b9c18a9

New binary : https://github.com/diyabc/diyabc/releases/tag/3.0.2

**Comment by fradav** [comment]
Oups, j'ai parlé trop vite, ça résoud le plantage, mais pas le -9999 du test de la stagiaire.
Gni. D'ailleurs il y avait bien que 3 pops dans son cas, c'est pour ça que ça ne plantait pas. À suivre

**Comment by fradav** [comment]
quand je génère les SML directement avec un fichier header à la mano : 
[header.txt](https://github.com/diyabc/diyabc/files/4427929/header.txt)
j'ai pas de -9999 mais que des zéros, est-ce le résultat attendu ?

**Comment by fradav** [comment]
Discussion : cas -9999 => renvoyer une valeur aléatoire uniforme entre 0.0 1.0

**Comment by fradav** [comment]
Done in 8c15817de211ad8e5b2de0d5ab7578b8511b6bef
