### ISSUE TITLE
Missing mutational values in first records text output

### ISSUE THREAD

**Issue by fradav** [diyabc/diyabc#20]
@elombaert : 

> Quand on simule des microsat et/ou des séquences, le fichier "first_record_of_the_reference_table.txt" est un peu bizarre : il ne contient aucune valeur pour les paramètres mutationnels. Le reftable.bin contient pourtant correctement ces informations (visible lorsqu’on le traduit avec abcrf sous R).

**Comment by fradav** [comment]
Fixed in 0e9747eb6d9033b3bd74c772474330c3be1efd95
@elombaert  : ça n'avait jamais été affiché correctement même dans diyabc 2.1.0, sauf erreur ?

**Comment by elombaert** [comment]
> Fixed in [0e9747e](https://github.com/diyabc/diyabc/commit/0e9747eb6d9033b3bd74c772474330c3be1efd95)
> @elombaert : ça n'avait jamais été affiché correctement même dans diyabc 2.1.0, sauf erreur ?

Si, ce tableau s'affichait correctement dans diyabc 2.1.0.
