### ISSUE TITLE
Réactiver l'option ABC prior/scenario checking

### ISSUE THREAD

**Issue by aestoup** [diyabc/diyabc#21]
Hello Francois-david,
Peux tu STP réactiver l'option suivante = ABC prior/scenario checking.
Apres discussion avec pas mal d'utilisateurs, c'est une option de "pre-traitement" tres appreciée!
Elle marche sur un reftable donc en principe pas de pbl a entrevoir.
J'ai deja vu avec Ghislain ou l'appeler dans l'interface.
Par avance merci.
A.

**Comment by fradav** [comment]
Fixed in 388e796abcd7d9e845d97ff1b1d0ee78daec5300
Binary : https://github.com/diyabc/diyabc/tree/3.0.4-beta
