### ISSUE TITLE
FST calculation failure (SNP)

### ISSUE THREAD

**Issue by elombaert** [diyabc/diyabc#22]
Salut François-David,
J’ai repéré un petit bug lors des calculs des stats résumées : **sur des données SNPs, il y a des problèmes de calculs des FST lorsque les populations concernées sont monomorphes.**
Par exemple, si lors d’une simulation les populations 1 et 2 sont monomorphes (ML1p_1 = 1 et ML1p_2 = 1), alors le FST2m_1.2 plantera ("NA"). Bien sûr, ça rend impossible, l’analyse par la suite avec AbcRanger ou abcrf.
J’en ai discuté ce matin avec Arnaud. Il s’agit vraisemblablement simplement d’un problème de division par 0. Il faudrait résoudre ce problème, et le plus simple serait de renvoyer un FST de 0 lorsque les populations sont monomorphes.
L’idée serait donc la suivante : faire un test ---> mettre Fst=0 quand **toutes** les pops impliquées dans un calcul de FST sont monomorphes à tous les locus (i.e. ML1p = 1), ceci pour Fst 1, 2, 3 ou 4 pops, que ce soit en IndSeq ou en PoolSeq (je n’ai pas vérifié pour le PoolSeq, mais la procédure de calcul doit être la même).
Si tu as des questions, n’hésite pas !

**Comment by fradav** [comment]
Ok je vais regarder ça

**Comment by fradav** [comment]
Fixed in 18c8b05656aa748024df697eb893b6a5aab42546
binary : https://github.com/diyabc/diyabc/releases/tag/3.0.4-beta2

**Comment by elombaert** [comment]
Salut,

Je viens de tester le nouveau binary 3.0.4-beta2. La simulation fonctionne sans accro, et il est possible d'utiliser AbcRanger par la suite a priori sans problème (pas de "NA" dans les FST).

Par contre :
- Le multithread ne fonctionne plus (donc simulations très longues).
- Il y a beaucoup trop de valeur à 0.000 pour les FST. Pour exemple, ici un fichier produit avec la nouvelle version beta2 :
[3.0.4-beta2_first_records_of_the_reference_table_1.txt](https://github.com/diyabc/diyabc/files/4667459/3.0.4-beta2_first_records_of_the_reference_table_1.txt)
Sur l'ensemble des 6 colonnes de FST2m, on trouve 778 valeur à 0.000, ce qui représente environ 20% des FST. A noter qu'il n'y a aucune population monomorphe sur l'ensemble de ce reftable.
Même analyses avec la version précédente (beta1) :
[3.0.4-beta1_first_records_of_the_reference_table_1.txt](https://github.com/diyabc/diyabc/files/4667458/3.0.4-beta1_first_records_of_the_reference_table_1.txt)
Ici, on ne trouve aucun FST à 0.000 (ce qui est beaucoup plus attendu).

**Comment by fradav** [comment]
Ok, je rouvre l'issue

**Comment by aestoup** [comment]
Comme l'a noté Eric; il semble effectivement y avoir un exces important de Fst=0.000.
En effet on voit dans 3.0.4-beta2_first_records_of_the_reference_table_1.txt que Fst=0.0000 dans des cas (voir cas deux pops) ou il y a du polymorphisme.
Il faut revoir a quel endroit dans le code tu declares Fst=0.000 quand tous les locus sont fixes pour le meme allele. 
Est ce que tu peux jeter un oeil STP?
On peut se faire un skype rapidement pour ca avev toi et Eric?

**Comment by fradav** [comment]
Ok, WIP

**Comment by fradav** [comment]
- fixed in aa05d51091d0a847a4d52edf45c743acfb09834e
- Release https://github.com/diyabc/diyabc/releases/tag/3.0.4-beta3

@elombaert le multicore a été remis (testé)

**Comment by elombaert** [comment]
J'ai fait les tests de la nouvelle version : tout semble fonctionner normalement, merci !
