### ISSUE TITLE
Incorrect "first_records_of_the_reference_table_0.txt" file for microsatellites and sequences

### ISSUE THREAD

**Issue by elombaert** [diyabc/diyabc#24]
Voici un problème, discuté avec Arnaud ce matin, qui n'a a priori pas d'impacte sur les analyses :
Lors de la simulation d’un reftableRF.bin, un fichier "first_records_of_the_reference_table_0.txt" est produit. Lorsque les datas sont des microsatellites, des séquences, ou les deux en même temps, il y a un décalage qui se fait dans ce fichier (aucun problème en revanche lorsqu'il s'agit de SNPs), et il semble manquer des colonnes lorsqu’on arrive à la fin du fichier.

Un exemple (données microsats) :
[first_records_of_the_reference_table_0_MICROSAT.txt](https://github.com/diyabc/diyabc/files/4752489/first_records_of_the_reference_table_0_MICROSAT.txt)

Dans un éditeur de texte, on voit le décalage se faire à partir de la colonne « r », juste avant les paramètres mutationnels. Je n’arrive pas vraiment à comprendre ce qui se passe puisque les valeurs de cette colonne ne collent pas avec les distributions a priori, et on a des ranges très larges (de 10-4 à 10+3).
A noter que le reftable.bin semble par contre correcte : il est lu et visualisé avec succès avec abcrf.

**Comment by elombaert** [comment]
Salut François-David,
Arnaud est à fond dans le beta-testing de l'interface, et je commence de mon côté probablement vendredi ou en début de semaine prochaine. Avant de commencer, je me demandais si tu avais trouvé une solution pour cette histoire de "first_record_of-the_reference_table" ? Ce fichier n'est pas primordial pour le bon fonctionnement de l'analyse globale, mais j'avoue que je m'en sers souvent pour vérifier différentes petites choses.

**Comment by fradav** [comment]
Ok, je regarde

**Comment by fradav** [comment]
Il y a deux bugs différents. Le premier est un problème d'affichage, je le laisse sur cette issue.
Le deuxième bug concerne des paramètres mutationnels qui "sautent" dans le listing des valeurs du *.txt 
Le problème d'affichage est le suivant : JMC a supposé que les noms de stats ne feraient jamais plus de 14 caractères, ce qui est bien sûr faux, et il a "hardcodé" de 14 cette limite absolument partout dans son code. J'ai du enlever la limite pour l'affichage des stats, et j'ai laissé l'affichage des valeurs tel quel. Ce que je te propose c'est une ligne de commande sed qui transforme le tout en csv que tu peux lire avec n'importe quel tableur:
```shell
sed -r -e 's/^\s+//gm' -e 's/\s+$//gm' -e 's/\s{14}/,/mg' -e '/^scenario/! s/\s{,13}(\S+)/\1,/mg' -e 's/\s+/,/mg' first_records.txt
```
Je marque cette issue en "wont fix"
