### ISSUE TITLE
Missing parameter in generated headerRF.txt file

### ISSUE THREAD

**Issue by gdurif** [diyabc/diyabc#26]
With the following file:

[header.txt](https://github.com/diyabc/diyabc/files/4826221/header.txt)

and the following command:
```bash
diyabc -p ./ "-n 't:4'"
diyabc -p ./ -R "" -g 100 -r 10 -m -t 4
```

The rate admixture parameter `ra` is missing on the final line of the generated `headerRF.txt` file.

**Comment by fradav** [comment]
le code de JMC suppose que les noms de params + espaces prennent au moins 14 chars :
```cpp
	this->entetehist = this->entete.substr(0, this->entete.length() - 14 * (nparamut + nstat));
```
(avec nstat = 2 et nparamut = 0, this->entete.length() = 82
du coup : 
```plain
scenario    N1    N2    N3    N4    t431    t32    t21    ra    HP0_1_1    HP0_1_2
```
est tronqué en
```plain
scenario    N1    N2    N3    N4    t431    t32    t21
```
Je préfère éviter de toucher à ce ******, est-ce que tu peux simplement mettre l'espacement requis dans la génération du header.txt ?

**Comment by gdurif** [comment]
Ok, j'ai juste pas compris, il faut que ça fasse max 14 char ou min 14 char ? si il y a beaucoup de paramètres, ça risque de pas tenir en 14 char
