### ISSUE TITLE
Double Checking FST mono pop code

### ISSUE THREAD

**Issue by fradav** [diyabc/diyabc#3]

**Comment by aestoup** [comment]
Problemo resoluto. J'ai produits par simulation DIYABC des nouvelles data POOLSEQ et INDSEQ (SNP classique) avec cette fois ci un minimum read count (parametre de filtrage des data poolseq simulées) MRC=0 (au lieu de MRC=3).

Resultat: tout est ok = on ne voit plus le biais que l'on observait sur les valeurs de Fst-monopop. Pouir confirmer j''ai produit et analysé des data INDSEQ (SNP classique) sans filtre aussi (cf. pas de MAF) et la aussi tout est ok (pas de biais).

En bref le biais observé auparavant était "normal" dans le sens ou il est généré par le filtre sur les data poolseq. En conclusion les Fst-monopop implémentées dans DIYABC sont ok! Pas besoin de verifier le code!!!

**Comment by fradav** [comment]
Exact matches obtained for fst/hb/hw compared with ad hoc calculations from Renaud, many thanks to him.
