### ISSUE TITLE
Multi-threading not working anymore

### ISSUE THREAD

**Issue by gdurif** [diyabc/diyabc#30]
The following training set simulation run
```bash
diyabc -p ./ -n 't:4'
diyabc -p ./ -R "" -t 4 -m -g 100 -r 1000
```
does not run on 4 threads with latest `diyabc` release (3.0.5-beta1).

**Comment by fradav** [comment]
Fixed in c38939d
Release https://github.com/diyabc/diyabc/releases/tag/v1.0-RF
