### ISSUE TITLE
Missing parameters in final line of headerRF.txt

### ISSUE THREAD

**Issue by fradav** [diyabc/diyabc#37]
Je suis en train de travailler sur un real dataset exemple (human dataset) pour repondre a une requete d'un reviewer/editeur MER.
J'ai généré un headerRF.txt et un reftableRF.bin avec 12000 particules via les instructions windows en lignes suivantes:
diyabc-windows-20200914-1243.exe -p ./ -R "" -r 12000 -g 10 -m -t 4
Ca a été au bout sans pbl.
J'essaye a présent de faire du model choice (standard) avec la derniere version windows de abcranger via les instructions suivantes:
abcranger-windows-20200922-1105.exe -n 12000 -t 1000 -j 8 -o modelchoice_results
Ca plante tres rapidement = au moment du "read headers".
Pour info: quand j'essaye estimation parametre via l'instruction:
abcranger-windows-20200922-1105.exe -n 1900 -t 1000 -j 8 --parameter ra --chosenscen 2 --plsmaxvar 0.95 --noob 1000 -o estim_param_S1_ra
Ca plante exactement pareil a savoir  tres rapidement = au moment du "read headers".
Je te joint les fichiers.
[headerRF.txt](https://github.com/diyabc/diyabc/files/5310399/headerRF.txt)

[reftableRF.gz](https://github.com/diyabc/diyabc/files/5310407/reftableRF.gz)
[statobsRF.txt](https://github.com/diyabc/diyabc/files/5310409/statobsRF.txt)

**Comment by fradav** [comment]
OK: Peut etre pour aider
Quand j'utilise R pour lire reftableRF.bin et headerRF.txt ca plante aussi avec le message suivant (en rouge):
> name.reference.table <- "reftableRF.bin"
> reference.table <- readRefTable(filename = name.reference.table, header="headerRF.txt",N=10000)
Error in `[<-`(`*tmp*`, i, parambyscenh[[scen]][j], value = lparams[j]) : 
  subscript out of bounds

Question: Ca t'inspire comme ca? Je ne sais pas si le message en rouge concerne le headerRF.txt ou le reftableRF.bin.
Pour rappel avec abcranger  ca plante tres rapidement = au moment du "read headers"...pbl plutot dand le header (que dans le reftable.bin)?

**Comment by fradav** [comment]
Dans ce cas precis ca bug pas = le headerRF.txt produit contient tous les parametres dans la derniere ligne (et pourtant les deux header.txt sont assez "proches").
[header (1).txt](https://github.com/diyabc/diyabc/files/5310420/header.1.txt)
[headerRF.txt](https://github.com/diyabc/diyabc/files/5310421/headerRF.txt)
[human_snp_all22chr_maf1%.snp.txt](https://github.com/diyabc/diyabc/files/5310423/human_snp_all22chr_maf1.snp.txt)

**Comment by fradav** [comment]
(All previous comments are collected excerpts from @aestoup mails)

**Comment by fradav** [comment]
'ai trouvé le pbl !!!

Dans mon cas Il y a 21 parametres:

header.txt (ancienne génération cf. stats avec des &) = derniere ligne OK pour ce qui est des parametres
scenario      N1            N2            N3            N4            t1            t2            d3           Nbn3           d4           Nbn4          N34            t3           d34          Nbn34           t4            Na            ra           t11           t22           t33           t44         HP0_1_1       HP0_1_2       HP0_1_3       HP0_1_4       HM1_1_1       HM1_1_2       HM1_1_3       HM1_1_4       HV1_1_1       HV1_1_2       HV1_1_3       HV1_1_4       HMO_1_1       HMO_1_2       HMO_1_3       HMO_1_4      FP0_1_1&2     FP0_1_1&3     FP0_1_1&4     FP0_1_2&3     FP0_1_2&4     FP0_1_3&4     FM1_1_1&2     FM1_1_1&3     FM1_1_1&4     FM1_1_2&3     FM1_1_2&4     FM1_1_3&4     FV1_1_1&2     FV1_1_1&3     FV1_1_1&4     FV1_1_2&3     FV1_1_2&4     FV1_1_3&4     FMO_1_1&2     FMO_1_1&3     FMO_1_1&4     FMO_1_2&3     FMO_1_2&4     FMO_1_3&4     NP0_1_1&2     NP0_1_1&3     NP0_1_1&4     NP0_1_2&3     NP0_1_2&4     NP0_1_3&4     NM1_1_1&2     NM1_1_1&3     NM1_1_1&4     NM1_1_2&3     NM1_1_2&4     NM1_1_3&4     NV1_1_1&2     NV1_1_1&3     NV1_1_1&4     NV1_1_2&3     NV1_1_2&4     NV1_1_3&4     NMO_1_1&2     NMO_1_1&3     NMO_1_1&4     NMO_1_2&3     NMO_1_2&4     NMO_1_3&4    AP0_1_1&2&4   AP0_1_1&2&3   AP0_1_1&3&4   AP0_1_2&1&3   AP0_1_2&1&4   AP0_1_2&3&4   AP0_1_3&1&2   AP0_1_3&1&4   AP0_1_3&2&4   AP0_1_4&2&3   AP0_1_4&1&3   AP0_1_4&1&2   AM1_1_1&2&4   AM1_1_1&2&3   AM1_1_1&3&4   AM1_1_2&1&3   AM1_1_2&1&4   AM1_1_2&3&4   AM1_1_3&1&2   AM1_1_3&1&4   AM1_1_3&2&4   AM1_1_4&2&3   AM1_1_4&1&3   AM1_1_4&1&2   AV1_1_1&2&4   AV1_1_1&2&3   AV1_1_1&3&4   AV1_1_2&1&3   AV1_1_2&1&4   AV1_1_2&3&4   AV1_1_3&1&2   AV1_1_3&1&4   AV1_1_3&2&4   AV1_1_4&2&3   AV1_1_4&1&3   AV1_1_4&1&2   AMO_1_1&2&4   AMO_1_1&2&3   AMO_1_1&3&4   AMO_1_2&1&3   AMO_1_2&1&4   AMO_1_2&3&4   AMO_1_3&1&2   AMO_1_3&1&4   AMO_1_3&2&4   AMO_1_4&2&3   AMO_1_4&1&3   AMO_1_4&1&2
headerRF.txt généré a partir de header.txt = dernière ligne pas ok = seulement 3 parametres !!! (sur les 21)
scenario      N1            N2            N3          ML1p_1        ML1p_2        ML1p_3        ML1p_4       ML2p_1.2      ML2p_1.3      ML2p_1.4      ML2p_2.3      ML2p_2.4      ML2p_3.4     ML3p_1.2.3    ML3p_1.2.4    ML3p_1.3.4    ML3p_2.3.4      HWm_1         HWm_2         HWm_3         HWm_4         HWv_1         HWv_2         HWv_3         HWv_4        HBm_1.2       HBm_1.3       HBm_1.4       HBm_2.3       HBm_2.4       HBm_3.4       HBv_1.2       HBv_1.3       HBv_1.4       HBv_2.3       HBv_2.4       HBv_3.4       FST1m_1       FST1m_2       FST1m_3       FST1m_4       FST1v_1       FST1v_2       FST1v_3       FST1v_4      FST2m_1.2     FST2m_1.3     FST2m_1.4     FST2m_2.3     FST2m_2.4     FST2m_3.4     FST2v_1.2     FST2v_1.3     FST2v_1.4     FST2v_2.3     FST2v_2.4     FST2v_3.4      NEIm_1.2      NEIm_1.3      NEIm_1.4      NEIm_2.3      NEIm_2.4      NEIm_3.4      NEIv_1.2      NEIv_1.3      NEIv_1.4      NEIv_2.3      NEIv_2.4      NEIv_3.4     AMLm_1.2.3    AMLm_2.1.3    AMLm_3.1.2    AMLm_1.2.4    AMLm_2.1.4    AMLm_4.1.2    AMLm_1.3.4    AMLm_3.1.4    AMLm_4.1.3    AMLm_2.3.4    AMLm_3.2.4    AMLm_4.2.3    AMLv_1.2.3    AMLv_2.1.3    AMLv_3.1.2    AMLv_1.2.4    AMLv_2.1.4    AMLv_4.1.2    AMLv_1.3.4    AMLv_3.1.4    AMLv_4.1.3    AMLv_2.3.4    AMLv_3.2.4    AMLv_4.2.3   FST3m_1.2.3   FST3m_1.2.4   FST3m_1.3.4   FST3m_2.3.4   FST3v_1.2.3   FST3v_1.2.4   FST3v_1.3.4   FST3v_2.3.4   FST4m_1.2.3.4  FST4v_1.2.3.4   F3m_1.2.3     F3m_2.1.3     F3m_3.1.2     F3m_1.2.4     F3m_2.1.4     F3m_4.1.2     F3m_1.3.4     F3m_3.1.4     F3m_4.1.3     F3m_2.3.4     F3m_3.2.4     F3m_4.2.3     F3v_1.2.3     F3v_2.1.3     F3v_3.1.2     F3v_1.2.4     F3v_2.1.4     F3v_4.1.2     F3v_1.3.4     F3v_3.1.4     F3v_4.1.3     F3v_2.3.4     F3v_3.2.4     F3v_4.2.3    F4m_1.2.3.4   F4m_1.3.2.4   F4m_1.4.2.3   F4v_1.2.3.4   F4v_1.3.2.4   F4v_1.4.2.3 
Je vois comment réparer ca "manuellement" (pour avancer un peu) mais ca serait bien de générer ASAP un exe windows DIYABC  clean notamment pour Ghislain et Eric (je les mets en copie car ils sont dessus actuellement).

Ghislain souhaite en effet produire un standalone ce mercredi suite a de gros bugs signalés lundi. Peut etre que aucune impacte mais a voir.

**Comment by fradav** [comment]
Well... j'ai parlé un peu vite:

- en corrigeant "a la mano" la derniere ligne du headerRF.txt (en mettant bien les 21 parametres):

- Ca marche alors parfaitement avec sous R abcrf = l'instruction reference.table <- readRefTable(filename =reftableRF.bin, header="headerRF.txt",N=12000) ne plante plus comme avant...et tout le(s) scripts(s) fonctionnent ok (model choice et parameter estimation)

- Ca marche en revanche toujours pas quand je lance abcranger-windows-20200922-1105.exe -n 12000 -t 1000 -j 8 -o modelchoice_results cf. comme avant Ca plante exactement pareil a savoir  tres rapidement = au moment du "read headers".

Bref, a moitié résolu et bien vérifier dans tous les cas que abcranger-windows produit un headerRF.txt clean notamment sur la deniere ligne (cf. nbre de parametres).

**Comment by fradav** [comment]
(All previous comments are collected excerpts from @aestoup mails)

**Comment by aestoup** [comment]
Voici comme convenu l

le header.txt + fichier de données (warning: enlever _ajout_extention_pour_transfert.txt que j'ai du ajouter pour que le fichier soit accepté cf. vrai nom = human_snp_all22chr_maf5%.snp) qui buggue sous windows en faisant crasher abcranger.

Pour rappel:

- on a 21 parametres dans le header.txt (inclu derniere ligne)

- on obtient seulement les trois premiers parametres dans la derniere ligne du headerRF.txt produit.
[header.txt](https://github.com/diyabc/diyabc/files/5313279/header.txt)
[human_snp_all22chr_maf5%.snp_ajout_extention_pour_transfert.txt](https://github.com/diyabc/diyabc/files/5313289/human_snp_all22chr_maf5.snp_ajout_extention_pour_transfert.txt)

Note: meme en ajoutant en dur les 21 parametre dans la derniere ligne du hederRF.txt ca plante en model choice (peut etre que le header codé dans le reftableRF.txt n'est plus "raccord").

**Comment by fradav** [comment]
Je confirme qu'il y a un problème spécifique à windows lors de la lecture des headers, (plus de stats!)

**Comment by aestoup** [comment]
OK: a toi de jouer Francois David. 
Si tu as besoin de moi (test ou autre diagnostic) just tell me.
A.

**Comment by fradav** [comment]
J'ai parlé trop vite, avec précisémment ces headers là, les stats sautent sous linux aussi : il y a juste N1,N2,N3

```text
group summary statistics (0)
group G1 (0)
scenario      N1            N2            N3      
```

**Comment by fradav** [comment]
Ok, c'est le parsing par windows de la ligne de commande pour l'arguments des stats SNP à filtrer (après le -R)
Comme pour windows "" = rien du tout on tombait sur l'argument d'après, qui ne correspond à aucune stats (par exemple -r).

Pour prévenir ce problème  en ligne de commande sous windows uniquement (pas de souci avec l'interface de ghislain)  il faut faire -R '""' et non pas -R ""
Fixed in 4ee15bc
Releases : https://github.com/diyabc/diyabc/releases/tag/v1.0.4-RF
