### ISSUE TITLE
Why diyabc can not simulate gene flow between populations?

### ISSUE THREAD

**Issue by xiekunwhy** [diyabc/diyabc#45]
Hi,

I just want to know why diyabc can not simulate gene flow between populations, and if I want to consider gene flow, any alternative   tools can do that?

Best,
Kun

**Comment by fradav** [comment]
@aestoup any word on this ? I'll close the issue otherwise.

**Comment by aestoup** [comment]
The coalescent algorithms implemented in DIYABC allow discrete (symetrical and asymetrical) admixture events (which can be seen as punctual cf. single generation geneflow events) but do not allow "standard gene flows" over time. This is clearly mentioned in the notice of the program (and in the publications associated to the program). Sorry about that.
