### ISSUE TITLE
How does diyabc recognize the population order in data file?

### ISSUE THREAD

**Issue by xiekunwhy** [diyabc/diyabc#46]
Hi,

How does diyabc-rf recognize the population order in data file? For example, there are five populations named "W_SIB, C_NC, W_NC, C_WC, W_WC" respectively in snp data file, which population will be treated as pop1?

Best,
Kun

**Comment by aestoup** [comment]
Pop1 = the first one in the observed dataset = W_SIB in your case.
Your last pop (W_WC) will be pop 5
Best
A.

**Comment by xiekunwhy** [comment]
Hi,

Thank you for youre answer.
And it seems that I need to order samples by populations at first.

Best,
Kun
