### ISSUE TITLE
Better identification of number of simulated data in output

### ISSUE THREAD

**Issue by gdurif** [diyabc/diyabc#47]
When simulating training set data, `diyabc` print the current number of simulated data (with a step corresponding to the batch size), e.g.

```
.
.
.
.
Ouverture du fichier
/tmp/RtmpMjF7Rc/diyabc_rf13a3334d5870/reftableRF.bin

nparammax=9
50
100
Total number of simulated loci : 98100
```

Instead of just a number, could that be possible to add a key word. e.g.
```
.
.
.
.
Ouverture du fichier
/tmp/RtmpMjF7Rc/diyabc_rf13a3334d5870/reftableRF.bin

nparammax=9
n simu data = 50
n simu data = 100
Total number of simulated loci : 98100
```
to simplify the output parsing to update progressbar in `diyabcGUI`.

**Comment by fradav** [comment]
Done in d51ee35
Release : https://github.com/diyabc/diyabc/releases/tag/v1.1.21
