### ISSUE TITLE
DIYABC_vFDR = commencer directement en lisant un fichier headerRF.txt ou un fichier header.txt.

### ISSUE THREAD

**Issue by aestoup** [diyabc/diyabc#48]
Hello Francois-David,

En reflechissant un peu je pense que ca serait top si DIYABC_vFDR pouvais commencer directement en lisant aussi bien un fichier headerRF.txt que un fichier header.txt.

Le gymnastique de passer par un header.txt sera tres deconcertante pour bc d'utilisateur lambda. Pouvoir lire un headerRF.txt permettra de produire eventuellement ce fichier via l'interface du standalone (windows ou autre)...et ensuite tout balancer en ligne de commande (sous linux ou autre environnement)

Concretement un minicode a jouter qui fasse la chose suivante: quand on lance en ligne de commande DIYABC_vFDC, le programme doit regarder si il y a un headerRF.txt dans le repertoire. Si il y en a un il le lis (recree un headerRF.txt a l'identique en principe) et run simues. Si il n'y en a pas alors il regarde si il y a un header.txt dans le repertoire et si il y en a un il le lis, creer un headerRF.txt et run simues (le truc classique actuel quoi). En gardant tout de meme la facon de faire actuelle ca permet de partir d'un header cree via l'interface de DIYABC_Cornuet ce qui peut etre utile/pratique.

**Comment by fradav** [comment]
Done in d1d8992
Release https://github.com/diyabc/diyabc/releases/tag/v1.1.22

**Comment by fradav** [comment]
Request to overwrite previous headerRF.txt instead of creating headerRFRF.txt for example.

**Comment by fradav** [comment]
FIxed in  0f82453 (along with a minor regression in windows build)
Release : https://github.com/diyabc/diyabc/releases/tag/v1.1.24
