### ISSUE TITLE
Major memory leak (Was "Serializing simulations")

### ISSUE THREAD

**Issue by fradav** [diyabc/diyabc#5]
Currently, big datasets are kept in-memory for simulations, and written once after all simulations ended. We need a dynamic serializer.

**Comment by aestoup** [comment]
This pbl is crucial as generating pseudo-observed raw datasets is a key option of DIYABC and that we need to do that cleanly especially or SNP cf. the type of data where dynamic serializing is crucial

**Comment by fradav** [comment]
Needs a working folder + command line to test simulation mode

**Comment by elombaert** [comment]
Est-ce que ceci te convient ? :
[dataset_test_multiple_types_2020_4_10-1.zip](https://github.com/diyabc/diyabc/files/4460624/dataset_test_multiple_types_2020_4_10-1.zip)
La ligne de commande ressemble à ça :
`./general -p ./ -k -m -t 4`

**Comment by elombaert** [comment]
Voici donc deux headersim SNP (pool et ind) :
[headersim.zip](https://github.com/diyabc/diyabc/files/4460872/headersim.zip)
Il y a également un petit readme avec des remarques et la ligne de commande.

**Comment by fradav** [comment]
@aestoup @elombaert  il manque un retour chariot avant la description des locii sinon ça fait planter tous les general de l'histoire (2.1.0, 2019 etc.)

Sinon ça ne génère pas grand'chose (example snp) :
```plain
Simulated genepop file   <NM=1NF>
POP
  1-001  , 
  1-002  , 
  1-003  , 
  1-004  , 
  1-005  , 
  1-006  , 
  1-007  , 
  1-008  , 
  1-009  , 
  1-010  , 
POP
  2-001  , 
  2-002  , 
  2-003  , 
  2-004  , 
  2-005  , 
  2-006  , 
  2-007  , 
  2-008  , 
  2-009  , 
  2-010  , 
POP
  3-001  , 
  3-002  , 
  3-003  , 
  3-004  , 
  3-005  , 
  3-006  , 
  3-007  , 
  3-008  , 
  3-009  , 
  3-010  , 
POP
  4-001  , 
  4-002  , 
  4-003  , 
  4-004  , 
  4-005  , 
  4-006  , 
  4-007  , 
  4-008  , 
  4-009  , 
  4-010  , 
```

J'ai loupé un truc?

**Comment by aestoup** [comment]
J'ai pourtant fait fonctionner cette option il y a peu de temps a partir de l'executable general-linux-20191127-1423

Pour ca j'ai tappé:

./general-linux-20191127-1423 -p ./ -k headersim.txt

en renommant en heardersim.txt soit headersim(_snp_10_ind_per_pop).txt soit headersim(_poolseq_100_ind).txt 

Attention: Eric a peut etre oublié de changer un nombre dans headersim(_snp_10_ind_per_pop).txt et dans headersim(_poolseq_100_ind).txt 

"loci description (30000)" doit en fait etre "loci description (100)" pour etre coherent avec le 100 en dessous. En effet initialement il y avait 30000 locus demandé au lieu de 100 et j'ai demandé a Eric de demander 100 locus (autrement trop long) mais il a du oublier de changer le nombre entre parenthese comme je te l'indique.

Essaye comme ca FD. Ca va marcher il n'y a pas de raison.
On fait un point lundi par mail ou par telephone si tu veux ou mardi a 14h par skype avec Eric

**Comment by aestoup** [comment]
Eric STP fait un test rapide de ton coté pour voir si ca tourne chez toi comme précisé ci-dessus. 
Je n'ai malheusement pas la possibilité de faire ca: vraiment désolé.
Je vais lundi tenter de m'equiper mieux la semaine prochaine pour pouvoir lancer qques trucs sur mon portable.

**Comment by fradav** [comment]
Oui maintenant ça  marche avec le general 2.1.0 et 2019 mais pas avec la dernière version (qui redonne la sortie vide plus haut)

**Comment by aestoup** [comment]
Ok on progresse.
Effectivement general-linux-20191127-1423 a ete fait en 2019. Ca ne marche pas pour les deux headersim (Indsim et poolsim) ou juste pour un (poolseq par exemple)?
hmmm...Je comprends pas ce qui a changé entre cette version general-linux-20191127-1423 et la derniere car tu as pas/peu touché a cette procedure de simulation de raw data.
Peut etre compare les procedures 2019 (qui marche) et la derniere de 2020 qui ne marche pas.
By the way, tu as deja probablement changé la variable pour le coverage (qui etait initialement en dur) pour le poolseq afin que on puisse l'appelervia l'interface (d'ou ma question sur le fait que ca ne marche pas que pour le poolseq)...mais je doute que ce soit ca.
On va y arriver!

**Comment by aestoup** [comment]
Note: il faut aussi peut etre UN SEUL retour charriot a la fin des fichiers headersim.txt cf. il me semble que les fichiers modifiés par Eric ont 2 retours charriots a la fin!

**Comment by elombaert** [comment]
Désolé pour le délai, je n'ai pas consulté mon mail pendant plus de 24H...
J'ai fait des tests, et ça ne marche pas à tous les coups :
- Je n'ai pas du tout réussi à simuler à partir du headersim.txt "pool".
- J'ai réussi à simuler des datasets avec le headersim.txt "individus", mais j'ai été obligé de rajouter des commandes dans la ligne proposée par Arnaud :
`./general-linux-20191127-1423 -p ./ -k headersim.txt  -m -t 8`
A noter également qu'il faut peut-être faire un petit "dos2unix" sur les fichiers car ils sont passés à un moment donné sous windows.

**Comment by fradav** [comment]
En fait c'est comme d'habitude avec le code de JMC : je trouve des palanquées de bugs que quand j'active le mode debug à la compilation. J'en ai un peu ras la casquette de nettoyer ses merdes derrière lui 10/15 ans après. 
"on s'en fout du moment que ça marche" : vous les biologistes vous êtes d'une arrogance hallucinante. Son code n'aurais jamais du survivre à son départ, c'est d'une aberration sans nom.

**Comment by aestoup** [comment]
Si on corrige les erreurs introduites fortuitement dans les deux headersim files:
- "loci description (30000)" --> "loci description (100)"
- Garder UN SEUL retour charriot a la fin des fichiers headersim.txt 
alors ca tourne nickel pour IndSeq et PoolSeq quelque soit l'executable (2019 ou 2020) en utilisant la ligne de commande:
./general-linux-20191127-1423 -p ./ -k headersim.txt
(en renommant en heardersim.txt soit headersim(_snp_10_ind_per_pop).txt pour IndSeq soit headersim(_poolseq_100_ind).txt pour PoolSeq)

**Comment by fradav** [comment]
@aestoup Ce que tu demandes c'est impossible sans réécrire toute la fonction de simu. En effet on boucle sur les locus mais quand on sort dans le fichier on sort individu par individu... ça suppose d'avoir calculé tous les locus pour sortir un seul individu : format de merde!
Une solution pourrait être d'écrire les données par locus sur chaque ligne dans un fichier "temporaire" et de s'en servir pour "transposer" à la fin. T'en penses quoi ? ça risque de prendre un peu de temps à coder par contre.

**Comment by aestoup** [comment]
OK je vois. Ca dois etre ca pour INdSeq (SNP classique vu le format final du heu de donné). Par contre pas sur que meme pbl pour PoolSeq car structure de donné différent. Tu peux verifier ca STP?
Avec un peu de chance ca sera plus simple pour PoolSeq.
 Ceci dit pour IndSeq la solution que tu proposes fait sens = "écrire les données par locus sur chaque ligne dans un fichier "temporaire" et de s'en servir pour "transposer" à la fin". Go for it et tant pis si ca prends un peu de temps car actuellement cette fonction (pas mal utilisée par c ertains utilisateurs) ne permet pas de generer des gros datasets sans faire péter la memoire!
Pour PoolSeq: verifier comme je le suggere plus haut et aviser alors si meme solution que pour IndSeq ou solution plus simple.

**Comment by fradav** [comment]
Effectivement, y'a pas ce problème pour les poolseq, les locus sont par ligne. Pour indseq, on peut pas faire autrement que tranposer. Ce que je ne comprends pas très bien, c'est que même si on fait ce gros hack de fichier temporaire et qu'on transpose, la simu produite va quand même être lue entièrement en mémoire à un moment donné, donc ça sert à quoi ?

**Comment by aestoup** [comment]
OK.
Donc no pbl pour poolseq c'est deja ca = faire comme on l'a discuté.

Pour IndSeq c'est vraiment dommage car c'est ce type de data (individuelles) qui sont les plus volumineuse a stocker en memoire.  En fait naivement je pensais que l'on pouvais tout simplement ajouter des colonnes (et donc des locus/genotypes dans le cas IndSeq) a un fichier (le datafile produit en l'occurence)...et pas des lignes (ca je sais que c'est facile).
Si c'est possible on aurait un fichier "puit" (le datafile a produire) et un fichier "source" temporaire = les genotypes de 100 ou 1000 locus qui sera copié en mode colonne dans le fichier puit.

Autre possibilité pour IndSeq = ecrire un fichier temporaire en sequenciel dont la configuration colonne - ligne est inversée relativement au fichier final. Dans ce cas on peut ajouter au fur et a mesure les locus (sequenciellement)...une fois fini =on cree le fichier final en inversant ligne - colonne. J'espere etre a peu pres clair.

Autre possibilite  pour IndSeq= ecrire un ensemble de sous fichiers de 1000 locus (temporaires) et quand on a le compte "concaterner" tout ca?

Je ne suis pas informaticien donc vraiment desolé par avance pour la probable stupidité de mes suggestions mais j'espere qu'il y a tout de meme une solution pour ca.

Tiens nous au courant STP

**Comment by fradav** [comment]
Ok, le problème c'est pas la faisabilité en soi, c'est l'utilité : le fichier de simu généré sera de toute façon **LU** en mémoire intégralement par tout les softs possibles qui prennent en charge les formats de simu. Donc _ce sera le même problème de mémoire à l'utilisation_, à moins de "sérialiser" aussi tous ces softs là. À moins que Matthieu ait un outil magique qui sache faire ça et que vous comptez utiliser ?

**Comment by aestoup** [comment]
Il faut penser aux utilisateurs non specialistes (et pas a Mathieu!)

Je pense que la lecture du fichier final, aussi gros soit-il (jusqu'a un certain point effectivement), n'est pas le probleme. Mais je me trompe peut etre. La preuve: avec Mathieu on a recemment du ruser en concatenant "a la main" 10 fichiers en 1 pour avoir un gros fichier final car la memoire de mon gros ordi explosait lorsque je voulais produire directement le gros fichier (d'ou le saucissonage en 10 sous fichiers). Possible (probable) que bc (trop?) de choses sont gardées en memoire lors de la simulation des génotypes IndSeq.
- d'ou l'idee d'ecrire le fichier final en serie = par paquets de locus
- Note: les fichiers de data IndSeq quand ils sont chargés par DIYABC passent par une phase de recodage en binaire (cf. meme nom de fichier avec extention .bin) cf. tu as du le remarquer par exemple en lancant general sur l'exemple 4pop IndSeq...peut etre pour palier au pbl potentiel que tu evoques? 
- Peut etre que il faudrait tout simplement changer le format de stockage des data qui vont a la fin generer le fichier, par exemple avec un format "+ court / economique" pour eviter une memoire qui "explose" trop vite?

Dis moi ce que tu en penses. Soyons pragmatique: si pour toi c'est "mission impossible et pas utile", alors dommage pour les utilisateurs de cette option (qui seront limités sur les datasets générable) mais tant pis on laisse tomber.
On a qques autres petits points a craquer qui devraient etre plus simples.

**Comment by aestoup** [comment]
Bref, pour eviter de perdre trop de temps la dessus tu peux peut-etre te contenter de garder la procedure actuelle JMC et juste evaluer/tenter les astuces possible pour economiser au max de la memoire lors de la génése des data IndSeq...l'idee c'est a minima d'augmenter au moins un peu notre capacité a générer des gros fichiers.
Si tu veux que on en discute 15 min par skype pas de pbl. Just tell me.

**Comment by fradav** [comment]
Peut-être que ça serait plus simple vous m'expliquiez toi et Mathieu comment vous générez les fichiers et comment il les concatène : après je peux automatiser la procédure. Encore plus simple, on pourrait simplement l'intégrer dans le code R de l'interface de Ghislain.

ça va faire la troisième fois que je te le demande, et tu éludes la question : je comprends toujours pas ce que tu peux faire avec le "gros fichier" généré, tu arrives à le lire avec quoi ? Tu en fais un dataset d'observé pour DIYABC et ça marche ?

Pour l'instant je ne vois rien qui explose particulièrement la mémoire lors de la génération des locus, je peux essayer de "nettoyer" des vecteurs par ci par là mais j'y crois moyen comme je ne comprends rien au code de simu.

**Comment by aestoup** [comment]
Bien recu. STP on peut faire un skype rapidou maintenant ? Ca sera plus efficace. Par avance merci.

Voir aussi ci dessous.

Le 22/04/2020 à 11:45, fradav a écrit :
>
> Peut-être que ça serait plus simple vous m'expliquiez toi et Mathieu comment vous générez les fichiers et comment il les concatène : après je peux automatiser la procédure. Encore plus simple, on pourrait simplement l'intégrer dans le code R de l'interface de Ghislain.

C'est un cas trop "addoc" (voir ci-dessous)

> ça va faire la troisième fois que je te le demande, et tu éludes la question : je comprends toujours pas ce que tu peux faire avec le "gros fichier" généré, tu arrives à le lire avec quoi ? Tu en fais un dataset d'observé pour DIYABC et ça marche ?

Oui c'est pour faire des analyses DIYABC avec un attendu clean = pseudo-observed dataset du ms MER par exemple. Apres d'autres personnes utilises ces fichiers pour d'autres choses (c'etait le cas avec Mathieu)

> Pour l'instant je ne vois rien qui explose particulièrement la mémoire lors de la génération des locus, je peux essayer de "nettoyer" des vecteurs par ci par là mais j'y crois moyen comme je ne comprends rien au code de simu, j'y crois moyen.

OK

**Comment by aestoup** [comment]
Deux pistes a explorer (ccl du skype):
1/ cleaner les "branches" pour gagner en memoire (test via meme seeds)
ou/puis si marche pas
2/ serialisation dans fichier temporaire suivi de inversion a la fin

**Comment by aestoup** [comment]
Note: pour 2/ un test sur petit fichier de data généré via meme seeds avec procedure JMC et new procedure FRC serait cool aussi

**Comment by fradav** [comment]
Pour le 1/ J'ai rajouté une ligne qui "clear" les branches après obtention de chaque locus.
Pour l'instant sur le fichier de test que tu m'as fourni je n'observe aucune différence de comportement entre la version "clear branch" et la version normale. Je la mets dans la release, au cas où, mais je soupçonne qu'il n'y a pas ou peu de branches dans cet exemple pour que ça soit pertinent ici.

**Comment by fradav** [comment]
https://github.com/diyabc/diyabc/releases/tag/3.0.3-alpha

**Comment by fradav** [comment]
Nouvelle version avec nettoyage des branches ET des nœuds, tant qu'à faire.

**Comment by fradav** [comment]
Je confirme qu'après examen des traces, le nettoyage des branches et des nœuds par locus simulé n'a lieu qu'après la toute fin de la simu dans la version _normale_ de diyabc. Cette nouvelle version force donc ce nettoyage après chaque locus obtenu, et du coup on devrait voir une différence si le nombre de branches/nœuds  est conséquent.

**Comment by aestoup** [comment]
Excellent et bravo!
Note 1: objectif - pas d'altération du datafile généré? Un test comparatif de fichier(s) généré(s) serait bon a faire = a minima un test sur deux petit fichier de data générés a partir des meme seeds a savoir un fichier  avec procedure JMC et un fichier avec ta new procedure FRC.
Note 2: objectif - gain en memoire substantiel ? comparer la RAM occupée pour deux gros fichier de data générés ($)  a partir des meme seeds a savoir un fichier  avec procedure JMC et un fichier avec ta new procedure FRC.
($) par exemple = mon exemple headersim.txt avec 4 pops en demandant 100 individus par pop (50 males et 50 femelles) au lieu des 10 actuels et 20000 locus (au lieu de 100)
On fait un point bientot par skype.

**Comment by aestoup** [comment]
CCL: ca marche (pour IndSeq et PoolSeq) !!!! ceci uniquement si on fait une "clean" COMPLET (cf. instruction a  compléter)
1/ A verifier sur grosse configuration 300 ind par pop et 250000 locus SNP avec chiffrage memoire
2/ Tester cette astuce sur le SIMULATEUR ABC "central" avec chiffrage memoire et surtout verifier que les reftable.bin sont les meme avec les deux procedures !!!

**Comment by fradav** [comment]
Alors, ça c'est le general "normal" sans suppression de branches : 

![orig](https://user-images.githubusercontent.com/701587/80770540-daa34880-8b50-11ea-8466-aa8d96480545.png)
max à 120Go environ
Et le nouveau : 

![new](https://user-images.githubusercontent.com/701587/80770661-2229d480-8b51-11ea-9c84-12f0da3e9765.png)

max à - de 4Go environ

Les fichiers générés sont strictement identiques.

**Comment by fradav** [comment]
La bonne nouvelle c'est que c'est en fait la même boucle pour les simus ABC. Sur chaque particule calculée on passe de 3Go à ... 400Mo.
![origABC](https://user-images.githubusercontent.com/701587/80792690-6343d800-8b95-11ea-89a2-fa48c64a1226.png)
![newABC](https://user-images.githubusercontent.com/701587/80792701-6939b900-8b95-11ea-8e9e-58571f0d4fa3.png)

Les reftable sont identiques au bit près.

Il suffisait de deux lignes de code.... Sérieux mec, on passe **un peu** pour des bouffons 😄

**Comment by fradav** [comment]
Fixed in 6f4fb4ad1091c3f2ba0a120cd3e5303bcbec8df5
