### ISSUE TITLE
Simulations end early without error

### ISSUE THREAD

**Issue by SethMusker** [diyabc/diyabc#52]
```
~/bin/diyabc_1.1.24_compiled -p ./ -n "t:40"
~/bin/diyabc_1.1.24_compiled -p ./ -R ALL -r 220000 -g 100 -m -t 40
```
The above commands ran fine but simulations ended at 53400 instead of requested 220000.

Relevant section of the terminal output
```
n simu data = 52900
n simu data = 53000   (34 days 18 h 46 min )
n simu data = 53100
n simu data = 53200
n simu data = 53300
n simu data = 53400
locus=0   OK=2
locus=1   OK=2
locus=2   OK=2
locus=3   OK=2
locus=4   OK=2
```

Also attached terminal output log file and headerRF.txt. 12 scenarios. (Perhaps the problem is that 12 isn't a factor of 220000?)
[slurm-1030907.out.txt](https://github.com/diyabc/diyabc/files/6528625/slurm-1030907.out.txt)
[headerRF.txt](https://github.com/diyabc/diyabc/files/6528626/headerRF.txt)

Model testing etc. proceed without errors using the generated reftable.

Will try rerunning with the debug build and multiple of 12 and report back.

**Comment by fradav** [comment]
@aestoup commented to me : 
> 153000 locus is a very high number of locii for such small number of populations and samples and you should look monitor memory consumption. Nonetheless, it is dubious how useful is such an amount of locii, perhaps a better approach is to select more useful locii  (polymorphic ones for example with MAF=5%). 

We don't understand your remark about 12 isn't a factor of 220000: the number of scenarii and the number of simulated particles are note related to each other.

**Comment by jbucholz** [comment]
@fradav I am facing this same issue with SNP data in the R shiny GUI. It times out at a random locus but throws no error code in the run logs.

**Comment by SethMusker** [comment]
Thanks for the suggestion re filtering. I reran it but specified 240000 iterations and it completed without problems. The cluster node has 380Gb of memory so I'm not sure that was the issue.

The factor thing was just a wild guess. I realise it shouldn't matter.
