### ISSUE TITLE
header.txt is mandatory (despite headerRF.txt) when project directory is not working directory

### ISSUE THREAD

**Issue by gdurif** [diyabc/diyabc#60]
With a project directory `/path/to/proj_dir` containing a `headerRF.txt` file:
- running `diyabc-RF-linux-v1.1.24 -p ./ -m -t 6 -R ALL -g 50 -r 100` from the project directory works
- running `diyabc-RF-linux-v1.1.24 -p /path/to/proj_dir/ -m -t 6 -R ALL -g 50 -r 100` from outside the project directory does not work, an error is returned stating that it cannot find any `header.txt` file.

**Comment by fradav** [comment]
fixed in a8dd2fc
Release : https://github.com/diyabc/diyabc/releases/tag/v1.1.26
