### ISSUE TITLE
LOGU mutational parameter samples from [0; x]

### ISSUE THREAD

**Issue by fradav** [diyabc/diyabc#9]
Should from ]0; x] (otherwise potential nan)

**Comment by fradav** [comment]
@aestoup un exemple de header + dataset avec LOGU  stp ? je n'en trouve nulle part

**Comment by fradav** [comment]
C'est pas plutôt LU en fait ?

**Comment by fradav** [comment]
```cpp
double MwcGen::glogunif(double min, double max) {
	double u, logmin, logmax;
	logmin = log(min);
	logmax = log(max);
	u = logmin + (logmax - logmin) * this->random();
	//cout <<logmin<<"   "<<logmax<<"   "<<u<<"   "<<exp(u)<<"\n";
	return exp(u);
}
```

Bon alors une petite mise au point maths : ce n'est pas possible de faire une distribution log-uniform sur ![image](https://user-images.githubusercontent.com/701587/78236721-ae0cfa00-74da-11ea-96b6-c219f40fb9ce.png) : ça revient à faire une distribution uniforme sur
![image](https://user-images.githubusercontent.com/701587/78236625-8b7ae100-74da-11ea-9939-a18113edb5a8.png), ce qui est impossible. Il faut obligatoirement une borne inférieure strictement positive. Je ferme ce ticket.

**Comment by aestoup** [comment]
Oui c'est le bon code a priori = Tirage dans une log-uniforme pour taux 
de mutation.

About ta mise au point math: JMC et moi on sait ca. En fait en theorie 
un taux de mutation n'est jamais egal a zero donc aucune raison de 
mettre taux mutation min a zero. C'est pour ca que on (JMC) n'avait pas 
blindé ca. Mais apparamment certains font ca. Donc blinder ce code en 
ecrivant si min = 0 alors faire min=0.000000001 (tres petit quoi). Vaut 
mieux ca que ecrire un message d'alerte dans l'interface!

OK comme ca?


Le 02/04/2020 à 12:09, fradav a écrit :

**Comment by fradav** [comment]
Ok pour faire min=0.000000001, si on a mis 0.
ça a n'a aucun sens pour moi mais bon soit.

**Comment by aestoup** [comment]
Il faut savoir etre pragmatique vis a vis des utilisateurs !!!

On va dire une valeur "proche de zero"--> min= le plus possible possible 
vu la precision machine cf. 0.000000001 c'est un exemple


Le 03/04/2020 à 11:51, fradav a écrit :

**Comment by elombaert** [comment]
@aestoup, ta proposition de 10-9 ne me semble pas être non plus une valeur particulièrement basse pour un taux de mutation. Mais j'ai peut-être mal compris l'exercice.

**Comment by aestoup** [comment]
Il faut savoir etre pragmatique vis a vis des utilisateurs !!!

On va dire mettre une valeur "proche de zero"--> min= le plus petit 
possible vu la precision machine cf. _0.000000001 c'est un exemple mais 
c'est pas assez bas. Tu peux descendre a combien FD?_


Le 03/04/2020 à 12:07, Arnaud Estoup a écrit :

**Comment by fradav** [comment]
2.2250738585072013830902327173324040642192159804623318306e-308 en double précision

**Comment by fradav** [comment]
Discussion : interdire la borne inférieure à 0 dans l'interface c'est pour @gdurif
